name: Deploy docs to GitHub Pages via mkdocs

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - name: clear CF cache
        run: |
          curl -X GET "https://api.cloudflare.com/client/v4/user/tokens/verify" \
          -H "Authorization: Bearer ${{ secrets.CLOUDFLARE_CLEAR_CACHE }}" \
          -H "Content-Type:application/json"
      - name: Set up Python ${{ matrix.python-version }} and deploya
        uses: actions/setup-python@v2.3.1
        with:
          python-version: 3.x
        run: pip install -r docs/requirements.txt
        run: mkdocs gh-deploy --force
