name: Deploy docs to GitHub Pages via mkdocs

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v3.1.1
        with:
          python-version: 3.x
      - run: |
          curl -X GET "https://api.cloudflare.com/client/v4/user/tokens/verify" \
          -H "Authorization: Bearer ${{ secrets.CLOUDFLARE_CLEAR_CACHE }}" \
          -H "Content-Type:application/json"
          pip install -r docs/requirements.txt
          mkdocs gh-deploy --force
