name: Lint

on: [push, pull_request]

jobs:
  editorconfig-checker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - name: editorconfig-checker
        run: |
          docker run --rm -v ${GITHUB_WORKSPACE}:/check mstruebing/editorconfig-checker

  yamllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - name: yamllint
        run: |
          find ~+ ${github_workspace} -name '*.yaml' -o -name '*.yml' | xargs docker run --rm -v ${GITHUB_WORKSPACE}:${GITHUB_WORKSPACE} peterdavehello/yamllint yamllint -d '{extends: default, rules: {document-start: {present: false}, line-length: disable}}'
